In [14]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
N_IN_GRAM = 1
MAX_FEAT = 2500

In [16]:
df = pd.read_csv("C:/Users/Samuel Samosir/Documents/Python/Kuliah/TA/benchmarking-sentiment-analysis-teks-indonesia/Dataset/templated/templated_posneg_data_bersih_helmi.csv", sep=";;;", engine='python', header=0)
df

teks  label
0            sangat memuaskan untuk perjalanan ke jogja      1
1                       kamar yang nyaman dan unik suka      1
2     hotel direkomendasikan banget deh pokoknya pel...      1
3     sangat menyenangkan lokasinya yang dekat dari ...      1
4                       pelayanan yang baik mudah akses      1
...                                                 ...    ...
4995  kamarnya kotor dan kesan tidak terurus sangat ...      0
4996  room saya deluxe tapi seperti tidak terawat be...      0
4997  kemarnya lembab baunya kurang sedap tirai kama...      0
4998  lantai rusak dan dinding banyak yang mengelupa...      0
4999  speri yang di di minta ganti tidak di ganti da...      0

[5000 rows x 2 columns]

In [17]:
unigram = CountVectorizer(ngram_range=(1, N_IN_GRAM), max_features=MAX_FEAT)
unigram_matrix = unigram.fit_transform(df['teks'].tolist())
feat_name = unigram.get_feature_names()

print(unigram_matrix.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
