In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
df = pd.read_csv("C:/Users/Samuel Samosir/Documents/Python/Kuliah/TA/benchmarking-sentiment-analysis-teks-indonesia/Dataset/templated/templated_posneg_data_bersih_helmi.csv", sep=";;;", engine='python')
df['teks']

0              sangat memuaskan untuk perjalanan ke jogja
1                         kamar yang nyaman dan unik suka
2       hotel direkomendasikan banget deh pokoknya pel...
3       sangat menyenangkan lokasinya yang dekat dari ...
4                         pelayanan yang baik mudah akses
                              ...                        
4995    kamarnya kotor dan kesan tidak terurus sangat ...
4996    room saya deluxe tapi seperti tidak terawat be...
4997    kemarnya lembab baunya kurang sedap tirai kama...
4998    lantai rusak dan dinding banyak yang mengelupa...
4999    speri yang di di minta ganti tidak di ganti da...
Name: teks, Length: 5000, dtype: object

In [6]:
unigram = CountVectorizer(ngram_range=(1, 1))
unigram_matrix = unigram.fit_transform(df['teks'].tolist())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
